version: "3.8"

services:
  postgresDB:
    image: postgres:14-alpine
    container_name: postgresDB
    restart: unless-stopped
    env_file: ./.env
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    ports:
      - $POSTGRES_LOCAL_PORT:$POSTGRES_DOCKER_PORT
    volumes:
        - "./volumes/db:/var/lib/postgresql/data"

  urlShortener:
    depends_on:
      - postgresDB
    image: urlshortener
    container_name: url-shortener
    build: .
    restart: on-failure
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    environment:
      POSTGRES_HOST: postgresDB
      POSTGRES_PORT: $POSTGRES_DOCKER_PORT
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    volumes:
      - ./logs:/logs